"""Application-owned contract for communicating with a vehicle."""

from typing import Protocol

from app.domain import Mission, Vehicle


class VehiclePort(Protocol):
    """Define vehicle operations without selecting a vehicle SDK or transport."""

    def connect(self, vehicle: Vehicle) -> None: ...

    def disconnect(self, vehicle: Vehicle) -> None: ...

    def arm(self, vehicle: Vehicle) -> None: ...

    def disarm(self, vehicle: Vehicle) -> None: ...

    def takeoff(self, vehicle: Vehicle) -> None: ...

    def land(self, vehicle: Vehicle) -> None: ...

    def execute_mission(self, mission: Mission) -> None: ...

    def return_to_home(self, vehicle: Vehicle) -> None: ...

    def emergency_stop(self, vehicle: Vehicle) -> None: ...
